replicaCount: 1

image:
  repository: viniciusbaratt0mat0s/projetojack
  tag: "latesd"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

labels:
  desafio: jackexperts

resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
  requests:
    memory: "64Mi"
    cpu: "250m"

ingress:
  enabled: true
  hosts:
    - host: 192.168.58.1 
      paths:
        - path: /
          pathType: Prefix