apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Chart.Name }}
    desafio: jackexperts
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-alt
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
